### ISSUE TITLE
Add more Tracker?

### ISSUE THREAD

**Issue by DennLie** [UPC-ViRVIG/SparsePoser#2]
Hello,
im playing around with the unityVr scene and it is working fine. Now i wonder if it is possible that i could add 2 more tracker for the elbows and if yes how?

**Comment by JLPM22** [comment]
Hi, thank you for trying our project!

Currently, the system does not support additional trackers. Modifying the network's architecture and retraining the system would be necessary. On the python side, it would be necessary to add elbows as additional sparse joints and probably modify a little the pooling code.
