### ISSUE TITLE
How do we use future frames?

### ISSUE THREAD

**Issue by Lucifer-G0** [UPC-ViRVIG/SparsePoser#5]
I have some confusion regarding the future frames mentioned in your paper. How are "ours-0" and "ours-7" defined? The convolution across the temporal dimension in the code uses padding of seven frames front and back, with a window of 15. Does this imply that it uses 7 future frames? In the experimental section, you mention a window of 64 frames with 7 future frames. What does the mention of a 64-frame window with 7 future frames mean in the experimental section? Does this refer to a convolution window of 64 frames?

**Comment by JLPM22** [comment]
In both cases we have a window of 64 frames. Padding is added later, so if padding is 7, it will add 7 elements at the beginning and 7 elements at the end. It does not affect the 64 frames window size.

If I remember correctly, the way it works is the following:

We construct the 64 frames window of sparse poses. 
In ours-0 we use frames 1 to 63 to add previous sparse poses, and in frame 64 we add the current frame sparse pose, then we just read the frame 64 output for the predicted pose.
In ours-7 we use frames 1 to 56 to add previous sparse poses, in frame 57 we add the frame we want to process, and frame 58 to 64, we add the "future sparse poses". In this case we read the frame 57 from the output to generate the pose. Conceptually, this is equivalent to having our method running with 7 frames of delay with respect to the application. 

Hope it clarifies your question, let me know if you need further detail!

**Comment by Lucifer-G0** [comment]
Thank you very much for your patient explanation; 

I now have a clearer understanding of what you've described. The 64-frame window you mentioned serves as the basis for generating results for each frame. In ours-0 and ours-7, the number of future frames within this window differs. We pad this window and then apply a convolution with a kernel size of 15 along the temporal dimension, ultimately adopting the result of only one frame (the current frame) as the output. 

I haven't seen such operations in your provided train, eval, or unity code; are they simplified versions? Do you only employ this operation during the final result assessment as a means of data augmentation?

 This is my first encounter with such a concept, and I would be very grateful if you could further explain the principles and significance of this approach.
