### ISSUE TITLE
How to caculate smoothness?

### ISSUE THREAD

**Issue by Lucifer-G0** [UPC-ViRVIG/SparsePoser#6]
Thank you for your previous help. 

In your paper, you utilized jitter and velocity error as metrics for evaluating motion smoothness. I must admit that my mathematical skills are not strong, and I didn't quite grasp how to calculate these metrics from discrete joint motion data. Could you possibly share some code snippets or point me to resources that explain how these metrics are computed?

Many thanks again for your assistance.

**Comment by JLPM22** [comment]
Hi!

I remember I used this paper to learn how to calculate these metrics: https://github.com/Xinyu-Yi/TransPose
They have some code as well, the error metrics are computed here: https://github.com/Xinyu-Yi/TransPose/blob/main/articulate/evaluator.py#L269

Hope it helps!
